version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-library_db}
      POSTGRES_USER: ${POSTGRES_USER:-library_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-library_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_network
    restart: unless-stopped

  # Redis for Django-Q
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - library_network
    restart: unless-stopped

  # Django Web Application
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 4 --timeout 120 library_service.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./logs:/app/logs
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://${POSTGRES_USER:-library_user}:${POSTGRES_PASSWORD:-library_password}@db:5432/${POSTGRES_DB:-library_db}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - FINE_MULTIPLIER=${FINE_MULTIPLIER:-2.0}
      - SITE_URL=${SITE_URL:-http://localhost}
    depends_on:
      - db
      - redis
    networks:
      - library_network
    restart: unless-stopped

  # Django-Q Worker
  worker:
    build: .
    command: python manage.py qcluster
    volumes:
      - ./logs:/app/logs
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://${POSTGRES_USER:-library_user}:${POSTGRES_PASSWORD:-library_password}@db:5432/${POSTGRES_DB:-library_db}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - FINE_MULTIPLIER=${FINE_MULTIPLIER:-2.0}
      - SITE_URL=${SITE_URL:-http://localhost}
    depends_on:
      - db
      - redis
    networks:
      - library_network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - library_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  library_network:
    driver: bridge